/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webank_wedpr_ot_kkrt_NativeInterface */

#ifndef _Included_com_webank_wedpr_ot_kkrt_NativeInterface
#define _Included_com_webank_wedpr_ot_kkrt_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webank_wedpr_ot_kkrt_NativeInterface
 * Method:    newSender
 * Signature: (JJ[Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_ot_kkrt_NativeInterface_newSender
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
